nhnacademy-be7-nuri-books/nuri-books-view

src/main/java/shop/nuribooks/view/auth/controller/AuthController.java
src/main/java/shop/nuribooks/view/auth/service/AuthService.java
src/main/java/shop/nuribooks/view/auth/service/AuthServiceImpl.java
src/main/java/shop/nuribooks/view/common/config/WebConfig.java
src/main/java/shop/nuribooks/view/common/feign/AuthServiceClient.java
src/main/java/shop/nuribooks/view/common/interceptor/AuthTokenInterceptor.java
src/main/java/shop/nuribooks/view/common/interceptor/LoginCheckInterceptor.java
src/main/java/shop/nuribooks/view/common/util/CookieUtil.java

Feature/login logout 로그인 로그아웃 구현

---

src/main/java/shop/nuribooks/view/admin/controller/AdminController.java
src/main/resources/templates/admin/admin.html
src/main/resources/templates/admin/admincategorycrud.html
src/main/resources/templates/layouts/adminlayout.html
src/test/java/shop/nuribooks/view/admin/controller/AdminControllerTest.java

관리자용 메인페이지 추가했습니다 디자인이나 내용 수정 환영입니다.

feature: 관리자 메인페이지 추가

---

src/main/resources/templates/admin/admin.html
src/main/resources/templates/admin/fragment/adminfooter.html
src/main/resources/templates/admin/fragment/adminheader.html
src/main/resources/templates/admin/fragment/adminsidebar.html
src/main/resources/templates/admin/layout/adminlayout.html

관리자 레이아웃 추가했습니다! 수정 필요 디자인 수정환영!!!!!!!!!

feature: 관리자 레이아웃 추가

---

.github/workflows/prod-deploy-actions.yml

feat: update cd

---

src/main/java/shop/nuribooks/view/Tag/dto/TagResponse.java
src/main/java/shop/nuribooks/view/Tag/feign/TagServiceClient.java
src/main/java/shop/nuribooks/view/Tag/service/TagService.java
src/main/java/shop/nuribooks/view/Tag/service/TagServiceImpl.java
src/main/java/shop/nuribooks/view/book/controller/AladinBookController.java
src/main/java/shop/nuribooks/view/book/controller/BookController.java
src/main/java/shop/nuribooks/view/book/dto/AladinBookSaveRequest.java
src/main/java/shop/nuribooks/view/book/dto/BookContributorsResponse.java
src/main/java/shop/nuribooks/view/book/feign/BookServiceClient.java
src/main/java/shop/nuribooks/view/book/service/BookService.java
src/main/java/shop/nuribooks/view/book/service/BookServiceImpl.java
src/main/java/shop/nuribooks/view/bookcontributor/dto/BookContributorInfoResponse.java
src/main/resources/application.yml
src/main/resources/templates/book/aladinBookList.html
src/main/resources/templates/book/bookList.html
src/main/resources/templates/book/bookRegister.html

Feature/book 외부api 이용 도서 등록, 도서 목록조회

---

src/main/java/shop/nuribooks/view/Tag/service/TagService.java
src/main/java/shop/nuribooks/view/admin/tag/dto/TagResponse.java
src/main/java/shop/nuribooks/view/admin/tag/feign/TagServiceClient.java
src/main/java/shop/nuribooks/view/admin/tag/service/TagService.java
src/main/java/shop/nuribooks/view/admin/tag/service/TagServiceImpl.java
src/main/java/shop/nuribooks/view/book/controller/AladinBookController.java
src/main/java/shop/nuribooks/view/book/controller/BookController.java
src/main/java/shop/nuribooks/view/book/dto/BookContributorsResponse.java
src/main/java/shop/nuribooks/view/book/dto/BookResponse.java
src/main/java/shop/nuribooks/view/book/feign/BookServiceClient.java
src/main/java/shop/nuribooks/view/book/service/BookService.java
src/main/java/shop/nuribooks/view/book/service/BookServiceImpl.java
src/main/resources/templates/book/bookDetail.html
src/main/resources/templates/book/bookList.html
src/main/resources/templates/book/bookRegister.html

Feature/book detail 도서 관련 구현 2차

---

src/main/java/shop/nuribooks/view/common/filter/AdminCheckFilter.java

/admin/** 요청 시, 관리자 권한을 체크하는 필터입니다.

Fix/admin : 관리자 페이지에 대한 권한 체크

---

src/main/resources/application.yml

* chore: front server CORS 설정 제거
- 불필요한 CORS 설정으로 삭제
* feat: samesite 설정 추가
* fix: samesite 옵션 수정

Feat/security samesite, secure 설정 수정 (#52)

---

pom.xml
src/main/java/shop/nuribooks/view/ViewApplication.java

* feat: redis 설정 추가
* feat: redis session 추가

Feat/redis redis session 의존성 추가 및 어노테이션 활성화 (#61)

---

src/main/java/shop/nuribooks/view/admin/shippingpolicy/controller/ShippingPolicyController.java
src/main/java/shop/nuribooks/view/admin/shippingpolicy/dto/ShippingPolicyRequest.java
src/main/java/shop/nuribooks/view/admin/shippingpolicy/dto/ShippingPolicyResponse.java
src/main/java/shop/nuribooks/view/admin/shippingpolicy/feign/ShippingPolicyServiceFeignClient.java
src/main/java/shop/nuribooks/view/admin/shippingpolicy/service/ShippingPolicyService.java
src/main/java/shop/nuribooks/view/admin/shippingpolicy/service/impl/ShippingPolicyServiceImpl.java
src/main/resources/templates/admin/shipping-policy/modal/delete_modal.html
src/main/resources/templates/admin/shipping-policy/modal/register_modal.html
src/main/resources/templates/admin/shipping-policy/modal/update_modal.html
src/main/resources/templates/admin/shipping-policy/shipping-policy.html

배송비 정책 CRUD Fornt 구현했습니다.
건우쿤의 레이아웃 덕분에 페이정처리까지 편하게 할 수 있었습니다.
Thanks, 제육 Guy!

feat: 배송비 정책 CRUD Front 구현

---

src/main/java/shop/nuribooks/view/auth/service/AuthServiceImpl.java
src/main/java/shop/nuribooks/view/oauth/common/utils/SecureRandomGenerator.java
src/main/java/shop/nuribooks/view/oauth/service/OAuth2MemberService.java
src/main/resources/templates/admin/fragment/adminsidebar.html
src/main/resources/templates/member/simple-signup.html

Member API에서 휴면회원 진행에 필요한 예외처리 메시지 처리하도록 수정했습니다!

fix: Auth API 예외처리 메시지 처리

---

src/main/java/shop/nuribooks/view/admin/coupon/controller/CouponController.java
src/main/java/shop/nuribooks/view/admin/coupon/dto/CouponRequest.java
src/main/java/shop/nuribooks/view/admin/coupon/dto/CouponResponse.java
src/main/java/shop/nuribooks/view/admin/coupon/feign/CouponServiceClient.java
src/main/java/shop/nuribooks/view/admin/coupon/service/CouponService.java
src/main/java/shop/nuribooks/view/admin/coupon/service/CouponServiceImpl.java
src/main/resources/templates/admin/coupon/coupon.html
src/main/resources/templates/admin/coupon/modal/delete_modal.html

쿠폰 관리 페이지에 활성화여부를 추가해서 삭제 대신 만료로 변경하고,
만료시 만료 일자가 나오게 수정했습니다 ~
땡스투 정책 guys~

feat: 쿠폰 삭제 대신 비활성화 구현

---

src/main/resources/templates/admin/coupon/coupon.html

6주차 중간 배포 (경민이 실수 해결!)

---

src/main/java/shop/nuribooks/view/admin/wrappingpaper/controller/WrappingPaperAdminController.java
src/main/java/shop/nuribooks/view/admin/wrappingpaper/dto/WrappingPaperRequest.java
src/main/java/shop/nuribooks/view/admin/wrappingpaper/dto/WrappingPaperResponse.java
src/main/java/shop/nuribooks/view/admin/wrappingpaper/feign/WrappingPaperServiceFeignClient.java
src/main/java/shop/nuribooks/view/admin/wrappingpaper/service/WrappingPaperService.java
src/main/java/shop/nuribooks/view/admin/wrappingpaper/service/impl/WrappingPaperServiceImpl.java
src/main/resources/templates/admin/fragment/adminsidebar.html
src/main/resources/templates/admin/shipping-policy/shipping-policy.html
src/main/resources/templates/admin/wrapping-paper/modal/delete_modal.html
src/main/resources/templates/admin/wrapping-paper/modal/register_modal.html
src/main/resources/templates/admin/wrapping-paper/modal/update_modal.html
src/main/resources/templates/admin/wrapping-paper/wrapping-paper.html

포장지 관리자 CRUD 및 view 구현했습니다.
포장지 이미지는 url로 관리되지만 이미지로 보이게 구현했습니다.
Thanks to Perfect guy 정규.

[Feature/wrapping paper] 포장지 관리자 CRUD 및 view 구현

---

src/main/resources/static/css/footer-style.css
src/main/resources/templates/fragments/footer.html
src/main/resources/templates/layouts/layout1.html

fix: footer 수정

---

src/main/java/shop/nuribooks/view/common/filter/TokenReissueFilter.java

post 요청 중 토큰 재발행이 일어나는 경우에 대해 처리했슴다!

fix: 307 상태 코드를 활용해 post 요청 시 토큰 재발행 이후 정상 처리

---

src/main/java/shop/nuribooks/view/auth/controller/AuthController.java
src/main/java/shop/nuribooks/view/common/sender/DoorayWebHookSender.java

refactor: 휴면 회원 url 수정

---

src/main/resources/templates/admin/fragment/adminsidebar.html
src/main/resources/templates/admin/shipping/shipping.html

fix: admin sidebar 수정

---

src/main/resources/templates/admin/shipping/shipping.html
src/main/resources/templates/admin/shipping/shipping_details.html

fix: N/A 메세지 대체 내용 수정

---

src/main/java/shop/nuribooks/view/order/order/controller/OrderController.java
src/main/resources/static/js/order/customerOrder.js
src/main/resources/static/js/order/memberOrder.js
src/main/resources/templates/member/order/order-detail.html
src/main/resources/templates/payment/fail.html
src/main/resources/templates/payment/success.html

- 결제 영역을 수정하였습니다.
- 주문 일부 html을 수정하였습니다.

Fix/order detail 주문 상세 로직 수정

---

src/main/java/shop/nuribooks/view/common/decoder/JwtDecoder.java

fix: 토큰 재발급을 위한 유효검사 로직 수정

---

src/main/java/shop/nuribooks/view/admin/coupon/controller/CouponController.java
src/main/java/shop/nuribooks/view/admin/coupon/dto/BookCouponResponse.java
src/main/java/shop/nuribooks/view/admin/coupon/feign/CouponServiceClient.java
src/main/java/shop/nuribooks/view/admin/coupon/service/CouponService.java
src/main/java/shop/nuribooks/view/admin/coupon/service/CouponServiceImpl.java
src/main/java/shop/nuribooks/view/book/controller/BookController.java
src/main/java/shop/nuribooks/view/member/coupon/controller/MemberCouponController.java
src/main/java/shop/nuribooks/view/member/coupon/feign/MemberCouponClient.java
src/main/java/shop/nuribooks/view/member/coupon/service/MemberCouponService.java
src/main/java/shop/nuribooks/view/member/coupon/service/MemberCouponServiceImpl.java
src/main/resources/templates/book/bookDetail.html

해당 도서에 쿠폰이 있는 경우에만 쿠폰발급 버튼을 활성화 했습니다.
쿠폰을 받은 경우에 대한 예외 처리 했습니다.

feat: 도서 상세페이지 도서쿠폰 발급 구현

---

src/main/resources/templates/admin/member.html
src/main/resources/templates/member/my-detail.html
src/main/resources/templates/member/my-edit.html
src/main/resources/templates/member/my-goodbye.html

refactor: 마이페이지에서 정보조회, 비밀번호 수정, 회원탈퇴 화면 수정

refactor: 마이페이지에서 정보조회, 비밀번호 수정, 회원탈퇴 화면 수정

---

src/main/java/shop/nuribooks/view/auth/controller/NomMemberController.java
src/main/java/shop/nuribooks/view/auth/dto/request/NonMemberRequest.java
src/main/java/shop/nuribooks/view/auth/dto/response/NonMemberResponse.java
src/main/java/shop/nuribooks/view/auth/service/NonmemberService.java
src/main/java/shop/nuribooks/view/common/feign/AuthServiceClient.java
src/main/resources/templates/auth/login.html
src/main/resources/templates/auth/non-login.html

feat: 비회원 주문 조회 Front 구현

---

src/main/java/shop/nuribooks/view/member/coupon/dto/CouponAppliedOrderDto.java
src/main/java/shop/nuribooks/view/order/order/controller/OrderController.java
src/main/java/shop/nuribooks/view/order/order/dto/OrderCancelDto.java
src/main/java/shop/nuribooks/view/order/order/feign/OrderServiceClient.java
src/main/java/shop/nuribooks/view/order/order/service/OrderService.java
src/main/java/shop/nuribooks/view/order/order/service/OrderServiceImpl.java
src/main/java/shop/nuribooks/view/payment/controller/PaymentController.java
src/main/resources/static/js/order/customerOrder.js
src/main/resources/static/js/order/memberOrder.js
src/main/resources/templates/member/fragment/membersidebar.html
src/main/resources/templates/member/order/cancel/cancel.html
src/main/resources/templates/member/order/my-cancelled-orders.html
src/main/resources/templates/member/order/order-detail.html

Feature/payment cancel 주문 취소 1차

---

src/main/java/shop/nuribooks/view/admin/batch/AdminBatchClient.java
src/main/java/shop/nuribooks/view/admin/batch/AdminBatchController.java
src/main/resources/templates/admin/batch/batch-list.html

feat: 관리자 배치 작업 생일쿠폰 적용

---

src/main/resources/static/js/order/customerOrder.js
src/main/resources/static/js/order/memberOrder.js

fix: 주문 로직 수정

---

src/main/java/shop/nuribooks/view/order/order/dto/OrderSummaryDto.java
src/main/java/shop/nuribooks/view/order/orderDetail/dto/OrderDetailItemDto.java
src/main/resources/static/js/order/memberOrder.js
src/main/resources/templates/member/order/order-detail.html

Fix/order qa  주문/주문 상세 로직 수정

---

src/main/java/shop/nuribooks/view/auth/dto/request/LoginRequest.java
src/main/java/shop/nuribooks/view/member/member/dto/request/MemberRegisterRequest.java
src/main/resources/templates/auth/login.html
src/main/resources/templates/member/sign-up.html

feat: 회원가입, 로그인 화면 실시간 유효성 검증, 로그인 유지 버튼 삭제

feat: 회원가입, 로그인 화면 실시간 유효성 검증

---

src/main/java/shop/nuribooks/view/book/controller/BookController.java
src/main/java/shop/nuribooks/view/book/dto/TopBookResponse.java
src/main/java/shop/nuribooks/view/book/feign/BookServiceClient.java
src/main/java/shop/nuribooks/view/book/service/BookService.java
src/main/java/shop/nuribooks/view/book/service/BookServiceImpl.java
src/main/java/shop/nuribooks/view/common/controller/HomeController.java
src/main/java/shop/nuribooks/view/review/dto/response/ReviewScoreResponse.java
src/main/java/shop/nuribooks/view/review/feign/ReviewServiceClient.java
src/main/java/shop/nuribooks/view/review/service/ReviewService.java
src/main/java/shop/nuribooks/view/review/service/impl/ReviewServiceImpl.java
src/main/resources/static/css/main-style.css
src/main/resources/templates/book/bookDetail.html
src/main/resources/templates/main/home.html

* feat: 도서 평점 관련 추가
* fix: 도서 상세페이지 수정

Fix/books 메인페이지 도서상세페이지 수정 (#186)

---

src/main/java/shop/nuribooks/view/admin/contributor/controller/ContributorController.java
src/main/java/shop/nuribooks/view/admin/contributor/dto/ContributorResponse.java
src/main/java/shop/nuribooks/view/admin/publisher/controller/PublisherController.java
src/main/java/shop/nuribooks/view/admin/publisher/dto/PublisherResponse.java
src/test/java/shop/nuribooks/view/admin/contributor/controller/ContributorControllerTest.java
src/test/java/shop/nuribooks/view/admin/contributor/service/ContributorServiceImplTest.java
src/test/java/shop/nuribooks/view/admin/coupon/controller/CouponPolicyControllerTest.java
src/test/java/shop/nuribooks/view/admin/coupon/service/CouponPolicyServiceImplTest.java
src/test/java/shop/nuribooks/view/admin/publisher/controller/PublisherControllerTest.java
src/test/java/shop/nuribooks/view/admin/publisher/service/PublisherServiceImplTest.java
src/test/java/shop/nuribooks/view/admin/shippingpolicy/controller/ShippingPolicyControllerTest.java
src/test/java/shop/nuribooks/view/admin/shippingpolicy/service/impl/ShippingPolicyServiceImplTest.java
src/test/java/shop/nuribooks/view/admin/tag/controller/TagControllerTest.java
src/test/java/shop/nuribooks/view/admin/tag/service/TagServiceImplTest.java
src/test/java/shop/nuribooks/view/admin/wrappingpaper/controller/WrappingPaperAdminControllerTest.java
src/test/java/shop/nuribooks/view/admin/wrappingpaper/service/impl/WrappingPaperServiceImplTest.java

출판사, 기여자, 태그, 배송 정책, 포장 정책, 쿠폰정책(1차) 에 대한 테스트 코드입니다~

test: 테스트 코드 구현

---

src/main/java/shop/nuribooks/view/order/orderDetail/dto/OrderDetailRequest.java
src/main/java/shop/nuribooks/view/order/stub/coupon/BookAppliedCouponRequestStub.java
src/main/resources/templates/order/contents/products-info.html
src/main/resources/templates/order/member-order-form.html

fix: 주문 - 필요없는 파일 제거
